"""Pre-effect refusal of writes to the operator's shared home (Redmine #14757 R2).

R1 detected mutations *after* they landed and failed the run. Review j#100407 R1-F1
/ j#100408 rejected that: acceptance 4 asks for the attempt to be **refused** and
acceptance 7 for **zero changes**, so a guard that lets the row land and then
reports it satisfies neither. This module is the missing layer, and its shape was
settled by measurement rather than by design intuition — two plausible mechanisms
were tried and discarded first (recorded in j#100411):

1. **A ``sitecustomize.py`` on ``PYTHONPATH`` — discarded.** ``PYTHONPATH`` is not
   inherited by a child started with ``env={}``, which is exactly the case
   acceptance 2/3 name (measured in j#100410).
2. **A ``sitecustomize.py`` in a task venv's ``site-packages`` — discarded.** The
   interpreter finds its site-packages without any env, so the reach is right, but
   the *name* is already taken: Homebrew's Python ships its own
   ``sitecustomize.py`` inside the **stdlib** directory, which precedes
   site-packages on ``sys.path``. Measured: ``sitecustomize.__file__`` resolved to
   Homebrew's copy, ours never ran, and an ``env={}`` child overwrote a file in the
   denied home with returncode 0. Shipping this would have left the hole while
   claiming it closed.
3. **A ``.pth`` file in a task venv's ``site-packages`` — adopted.** ``site``
   executes the ``import`` line of *every* ``.pth`` it finds, so there is no single
   name to shadow, and site-packages discovery is interpreter-relative. Measured:
   an ``env={}`` child attempting to overwrite an existing file in the denied home
   got ``PermissionError`` and the file's bytes were unchanged.

Two further properties matter:

- **The denied roots are baked into the generated module as literals**, not read
  from the environment. A hook that read ``os.environ`` would be disarmed by the
  very ``clear=True`` it exists to survive.
- **``PYTHONPATH`` is not used at all**, so #13733 j#78390 F1 (a ``src/`` entry
  leaking into a nested ``pip install``) is out of the design rather than argued
  around.

Reads are deliberately not refused: the objective is that shared schema/data is
never *changed*, and refusing reads would block the parent's own consistent
snapshot while buying nothing for the acceptance criteria.

**What this does not reach**, enumerated rather than glossed (j#100410 item 3): the
hook is installed by *this interpreter*, so a child launched through a hardcoded
``python`` / ``python3`` name, or through a venv a test creates itself, does not
carry it. Those spawn shapes are cataloged by
``tests/integration/.../test_test_home_isolation_runner.py`` so the standard suite
cannot acquire one silently.
"""

from __future__ import annotations

import json as _json
import subprocess
from uuid import uuid4
import sys
from pathlib import Path

#: Module the ``.pth`` imports. Underscore-prefixed and mozyo-specific so it
#: cannot collide with anything a test imports by accident.
FENCE_MODULE_NAME = "_mozyo_test_fence"

#: ``site`` processes ``.pth`` files in sorted order; the ``zz_`` prefix installs
#: the hook after any other path configuration has run.
FENCE_PTH_NAME = "zz_mozyo_test_fence.pth"

#: Task-specific virtualenv under the fence root. Its interpreter is what runs the
#: suite, and what every ``sys.executable`` child inherits.
VENV_DIRNAME = "venv"

#: Append-only JSONL of refused attempts. An empty ledger is the primary evidence
#: for acceptance 7 — attribution, not directory comparison (j#100408 finding_1).
LEDGER_FILENAME = "deny-attempts.jsonl"


class AuditHookInstallError(RuntimeError):
    """The pre-effect refusal layer could not be installed.

    Raised rather than warned: a run whose refusal layer is absent must not be
    reported as isolated (#14757 acceptance 3/4).
    """


# Generated per run with the denied roots and ledger path interpolated as
# literals. stdlib-only, imports no mozyo_bridge, and defensive throughout: it runs
# inside every descendant interpreter, where a traceback would break unrelated work
# rather than protect anything.
_FENCE_MODULE_TEMPLATE = '''"""Refuse writes to the operator's shared mozyo-bridge home (generated).

Generated by mozyo-bridge for one `tests run` invocation (Redmine #14757).
Do not edit: it is rewritten per run, inside a throwaway task venv.

The denied roots below are literals ON PURPOSE. Reading them from os.environ would
let `patch.dict(os.environ, {{}}, clear=True)` -- the very thing this guard exists
to survive -- disarm the guard.
"""

import os as _os
import sys as _sys

_DENIED = {denied!r}
_AUDIT_CANARY = {audit_canary!r}
_LEDGER = {ledger!r}

# --- outer boundary context: versioned typed contract (j#100447 Phase A item 1) --
# Recovered by `test_home_os_fence.load_outer_context()` in a nested run. Module
# literals, not env: `env={{}}` is exactly the case that must keep working. Every
# field is required; a missing or mistyped one is a typed refusal, never a fallback
# to building a second boundary (j#100445 item 1).
MOZYO_FENCE_CONTEXT_VERSION = 1
MOZYO_FENCE_ORIGIN_BACKEND = {origin_backend!r}
MOZYO_FENCE_OUTER_PROTECTED_ROOTS = {denied!r}
MOZYO_FENCE_TASK_ROOT = {task_root!r}
MOZYO_FENCE_CANARY_ROOT = {canary!r}
MOZYO_FENCE_ALLOWED_CONTROL_ROOT = {allowed_control_root!r}

# Legacy aliases (pre-j#100447). Kept so a half-updated reader cannot silently see
# nothing; new readers use the versioned names above.
MOZYO_FENCE_DENIED = _DENIED
MOZYO_FENCE_CANARY = {canary!r}

_MUTATING = {{
    "os.mkdir": (0,),
    "os.rmdir": (0,),
    "os.remove": (0,),
    "os.unlink": (0,),
    "os.truncate": (0,),
    "os.chmod": (0,),
    "os.chown": (0,),
    "os.utime": (0,),
    "os.rename": (0, 1),
    "os.replace": (0, 1),
    # For link-likes only the destination is created; the source is read.
    "os.link": (1,),
    "os.symlink": (1,),
    "shutil.copyfile": (1,),
    "shutil.copymode": (1,),
    "shutil.copystat": (1,),
    "shutil.copytree": (1,),
    "shutil.move": (1,),
    "shutil.rmtree": (0,),
}}

_WRITE_MODE_CHARS = frozenset("wxa+")
_WRITE_FLAGS = (
    _os.O_WRONLY | _os.O_RDWR | _os.O_APPEND | _os.O_CREAT | _os.O_TRUNC
)


def _install():
    roots = []
    # The audit canary is task-local scratch this hook also refuses, so the armed
    # self-check has a target that is NOT the operator's shared home (j#100483
    # item 4). It is deliberately absent from MOZYO_FENCE_OUTER_PROTECTED_ROOTS:
    # it is this generation's probe target, not shared state a nested run inherits.
    for entry in (*_DENIED, _AUDIT_CANARY):
        try:
            resolved = _os.path.realpath(_os.path.expanduser(entry))
        except Exception:
            continue
        if resolved:
            roots.append(resolved.rstrip(_os.sep))
    if not roots:
        return
    exact = frozenset(roots)
    prefixes = tuple(root + _os.sep for root in roots)
    state = {{"busy": False}}

    def _denied(raw):
        if raw is None:
            return None
        try:
            text = _os.fspath(raw)
        except TypeError:
            return None
        if isinstance(text, bytes):
            try:
                text = text.decode("utf-8", "surrogateescape")
            except Exception:
                return None
        if not isinstance(text, str) or not text:
            return None
        try:
            resolved = _os.path.realpath(_os.path.expanduser(text))
        except Exception:
            return None
        if resolved in exact:
            return resolved
        for prefix in prefixes:
            if resolved.startswith(prefix):
                return resolved
        return None

    def _record(event, target):
        # The ledger write is itself an audited `open`; disarm while recording.
        state["busy"] = True
        try:
            relative = target
            for root in exact:
                if target == root or target.startswith(root + _os.sep):
                    relative = target[len(root):].lstrip(_os.sep) or "."
                    break
            line = '{{"event": "%s", "target": "%s", "pid": %d}}\\n' % (
                str(event).replace('"', ""),
                relative.replace("\\\\", "/").replace('"', ""),
                _os.getpid(),
            )
            fd = _os.open(_LEDGER, _os.O_WRONLY | _os.O_CREAT | _os.O_APPEND, 0o600)
            try:
                _os.write(fd, line.encode("utf-8", "replace"))
            finally:
                _os.close(fd)
        except Exception:
            pass
        finally:
            state["busy"] = False

    def _refuse(event, target):
        _record(event, target)
        raise PermissionError(
            "mozyo-bridge test fence: refusing %s on the operator's shared "
            "mozyo-bridge home (%s). A test process must not write shared state; "
            "pass an explicit home= under the fenced task root." % (event, target)
        )

    def _hook(event, args):
        if state["busy"]:
            return
        if event == "open":
            try:
                mode = args[1]
                flags = args[2]
            except Exception:
                return
            writing = False
            if isinstance(mode, str) and _WRITE_MODE_CHARS.intersection(mode):
                writing = True
            elif isinstance(flags, int) and flags & _WRITE_FLAGS:
                writing = True
            if not writing:
                return
            target = _denied(args[0])
            if target is not None:
                _refuse(event, target)
            return
        if event == "sqlite3.connect":
            try:
                database = args[0]
            except Exception:
                return
            try:
                text = _os.fspath(database)
            except TypeError:
                return
            if isinstance(text, bytes):
                text = text.decode("utf-8", "surrogateescape")
            if not isinstance(text, str):
                return
            # A read-only / in-memory connection cannot mutate the file.
            if text == ":memory:" or "mode=ro" in text or "mode=memory" in text:
                return
            if text.startswith("file:"):
                text = text[5:].split("?", 1)[0]
            target = _denied(text)
            if target is not None:
                _refuse(event, target)
            return
        indexes = _MUTATING.get(event)
        if indexes is None:
            return
        for index in indexes:
            try:
                candidate = args[index]
            except Exception:
                continue
            target = _denied(candidate)
            if target is not None:
                _refuse(event, target)

    _sys.addaudithook(_hook)


try:
    _install()
except Exception:
    # Never break interpreter startup; record so the parent fails the run instead.
    try:
        with open(_LEDGER, "a", encoding="utf-8") as _fh:
            _fh.write(
                '{{"event": "install_failed", "target": ".", "pid": %d}}\\n'
                % _os.getpid()
            )
    except Exception:
        pass
'''


def venv_python(fence_root: Path) -> Path:
    """Path to the task venv's interpreter (POSIX and Windows layouts)."""
    root = Path(fence_root) / VENV_DIRNAME
    posix = root / "bin" / "python"
    return posix if posix.exists() else root / "Scripts" / "python.exe"


def install_audit_fence(
    fence_root: Path,
    *,
    denied_homes: tuple[Path, ...],
    canary: Path,
    origin_backend: str,
    allowed_control_root: Path,
    task_root: Path | None = None,
) -> tuple[Path, Path]:
    """Build the task venv and arm the refusal hook inside it.

    Returns ``(venv_python, ledger)``. Raises :class:`AuditHookInstallError` when
    any step fails — an un-armed run must not be mistaken for an isolated one.

    ``--system-site-packages`` keeps the base interpreter's packages importable, so
    the suite sees the same dependencies as an unfenced run; ``--without-pip``
    keeps creation cheap (measured ~0.06s, against a ~400s suite).
    """
    root = Path(fence_root)
    ledger = root / LEDGER_FILENAME
    ledger.write_text("", encoding="utf-8")

    venv_dir = root / VENV_DIRNAME
    try:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "venv",
                "--without-pip",
                "--system-site-packages",
                str(venv_dir),
            ],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", "") or str(exc)
        raise AuditHookInstallError(
            f"could not create the task venv that carries the write-refusal hook "
            f"({detail.strip()[:400]})"
        ) from exc

    python = venv_python(root)
    if not python.exists():
        raise AuditHookInstallError(f"task venv has no interpreter at {python}")

    try:
        site_packages = subprocess.run(
            [
                str(python),
                "-c",
                "import sysconfig; print(sysconfig.get_paths()['purelib'])",
            ],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as exc:
        raise AuditHookInstallError(
            f"could not resolve the task venv's site-packages ({exc})"
        ) from exc
    if not site_packages:
        raise AuditHookInstallError("task venv reported no site-packages directory")

    target = Path(site_packages)
    target.mkdir(parents=True, exist_ok=True)
    # Must exist before the self-check runs: against a missing directory an unarmed
    # hook fails with ENOENT, which reads as "unprovable" rather than the true
    # "not armed", and the two verdicts must stay distinguishable.
    audit_canary_for(fence_root).mkdir(parents=True, exist_ok=True)
    (target / f"{FENCE_MODULE_NAME}.py").write_text(
        _FENCE_MODULE_TEMPLATE.format(
            denied=tuple(str(path) for path in denied_homes),
            audit_canary=str(audit_canary_for(fence_root)),
            ledger=str(ledger),
            canary=str(canary),
            origin_backend=str(origin_backend),
            task_root=str(Path(task_root if task_root is not None else fence_root).resolve()),
            allowed_control_root=str(allowed_control_root),
        ),
        encoding="utf-8",
    )
    # `site` runs the import line of every .pth it finds, so unlike a module name
    # there is nothing here for the stdlib's own sitecustomize to shadow.
    (target / FENCE_PTH_NAME).write_text(
        f"import {FENCE_MODULE_NAME}\n", encoding="utf-8"
    )
    return python, ledger


def _ledger_records_attempt(raw: str, nonce: str) -> bool:
    """Does the ledger hold a well-formed record of exactly this attempt?

    Parsed as JSONL, not substring-matched (j#100489 F5). A substring test passes
    on a malformed line, on an unrelated record that merely quotes the name, and on
    a truncated write -- none of which show the hook acted. Requires one record
    with exactly ``event == "open"``, the exact nonce basename, and an int pid.
    """
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            record = _json.loads(line)
        except ValueError:
            continue
        if not isinstance(record, dict):
            continue
        if (
            record.get("event") == "open"
            and record.get("target") == nonce
            and type(record.get("pid")) is int
        ):
            return True
    return False


def audit_canary_for(fence_root: Path) -> Path:
    """The task-local directory the audit hook refuses, for the armed self-check.

    One definition, used by both the installer (which creates it) and the
    self-check (which writes into it), so the two cannot name different paths.
    """
    return Path(fence_root).resolve() / "audit-canary"


def verify_audit_fence(python: Path, fence_root: Path, ledger: Path) -> None:
    """Prove the hook is armed in ``python`` before trusting the run.

    Runs a probe with a **cleared environment** — the case that killed both
    discarded mechanisms — and requires the write to be refused. This is a
    self-check, not a test: it runs on every invocation, so a run can never report
    isolation that was silently absent (the failure mode of discarded mechanism 2,
    which reported success while the file was overwritten).

    The target is the **task-local audit canary**, never the operator's shared home
    (j#100483 item 4). Aiming a self-check at shared state means every run attempts
    a write there and relies on the very mechanism under test to stop it — and the
    earlier version of exactly this probe was removed for that reason (j#100445
    item 3). Refusal alone is also not enough: an unwritable path refuses too, so
    the hook must additionally be shown to have **recorded** the attempt in its own
    ledger. That is provenance — evidence the hook acted, not merely that the write
    did not land.
    """
    # A fresh name per self-check. The ledger deliberately records only the
    # basename -- it must never carry directory paths -- so a unique name is what
    # makes "the hook recorded THIS attempt" checkable without logging a path.
    probe = audit_canary_for(fence_root) / f".mozyo-fence-selfcheck-{uuid4().hex}"
    code = (
        "import sys\n"
        f"target = {str(probe)!r}\n"
        "try:\n"
        "    open(target, 'w').write('x')\n"
        "except PermissionError:\n"
        "    sys.exit(0)\n"
        "except OSError:\n"
        "    sys.exit(3)\n"
        "sys.exit(4)\n"
    )
    try:
        completed = subprocess.run(
            [str(python), "-c", code], env={}, capture_output=True, text=True
        )
    except OSError as exc:
        raise AuditHookInstallError(f"could not run the fence self-check ({exc})") from exc
    if completed.returncode == 0:
        # Refusal is necessary but not sufficient: prove the HOOK refused, by
        # finding its own record of the attempt. Without this, an unwritable or
        # missing path would read as a proven fence.
        try:
            recorded = Path(ledger).read_text(encoding="utf-8")
        except OSError as exc:
            raise AuditHookInstallError(
                f"the fence self-check was refused but its ledger could not be read "
                f"({exc}); the refusal has no provenance"
            ) from exc
        if not _ledger_records_attempt(recorded, probe.name):
            raise AuditHookInstallError(
                "the fence self-check write was refused, but the hook did not record "
                "a matching attempt in its ledger -- something other than the hook "
                "blocked it, so the hook is not proven armed"
            )
        return
    if completed.returncode == 4:
        raise AuditHookInstallError(
            "the write-refusal hook is NOT armed: a cleared-environment child was "
            "allowed to write inside the task-local audit canary this hook denies. "
            "Refusing to report this run as isolated."
        )
    if completed.returncode == 3:
        # A non-PermissionError OSError means the path was unwritable for an
        # unrelated reason, so the probe proves nothing either way.
        raise AuditHookInstallError(
            "the fence self-check could not distinguish refusal from an unrelated "
            "filesystem error; isolation is unproven"
        )
    raise AuditHookInstallError(
        f"the fence self-check failed unexpectedly (rc={completed.returncode}): "
        f"{(completed.stderr or '').strip()[:400]}"
    )


__all__ = (
    "FENCE_MODULE_NAME",
    "FENCE_PTH_NAME",
    "LEDGER_FILENAME",
    "VENV_DIRNAME",
    "AuditHookInstallError",
    "audit_canary_for",
    "install_audit_fence",
    "venv_python",
    "verify_audit_fence",
)
